[package]
name    = "code_grouper"
version = "1.7.0"
edition = "2024"

[lib]
name = "code_grouper"
path = "src/lib.rs"

[[bin]]
name = "code_grouper"
path = "src/main.rs"

[dependencies]
anyhow       = "1"
clap         = { version = "4.5", features = ["derive"] }
tempfile     = "3"
walkdir      = "2"

[dev-dependencies]
tempfile     = "3"
